workaround for ContextNotActiveException on login failure email notifications
If email notification are enabled for login failure events, the following exception occurs on RADIUS login failures:
  ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for CurrentVertxRequest

The ContextNotActiveException occurs on login failures when email notifications are enabled. This exception is not caused by the missing Arc context, but by the email event handler expecting an HTTP request context, which RADIUS requests never have.

This workaround catches the ContextNotActiveException and turns it into a non-critical log message. The events are still processed and stored by other handlers, as the email handler is in the last processing phase.